In [1]:
import numpy as np

A = np.array([(1,2,4),(5,3,7),(8,3,6)])
print(A)
print(np.unique(A))
print()

B = A[1:,1:]
print('B=',B)
print()


#Initially I wanted to look for min but we will see that np.unique allows us to find each value of interest in B :)
    #Id_init = np.unique(B)
    #print(Id_init)
    #print(B.min())
    #print(np.argmin(B))
    #print(np.amin(B))


#Best solution turns out to be np.where function

List = np.where(B == np.amin(B))
print('List=',List)
print(type(List))
print()

List_test_2 = np.where(B == np.unique(B))
print('List=',List_test_2)
print(type(List_test_2))
print()

ListOfCoordinates = list(zip(List[0], List[1]))
print('ListOfCoordinates=',ListOfCoordinates)
print(type(ListOfCoordinates))
print()

print('########################### FOR INFORMATION ###########################')
###Conversion is useless we can use directly the ListOfCoordinates to extract the value of interest in B ###
#We keep active those functions to show their nature
ListArray = np.array(ListOfCoordinates)
print('ListArray=',ListArray)
print(type(ListArray))
print()

ListArray_row0 = ListArray[0]
print('ListArray_row0=',ListArray_row0)
print(type(ListArray_row0))
print('ListArray_row0[0]=',ListArray_row0[0])
print(type(ListArray_row0[0]))
print()

x = B [1]
print('x=',x)
print(type(x))
print()

y = B [1,1]
print('y=',y)
print(type(y))
print()

z = B[[1,1]]
print('z=',z)
print(type(z))
print()


print('#####################################################################')
print()

#THE ONLY USEFULE NOTATION IN THIS PROBLEM:
w = B[(1,1)]
print('w=',w)
print(type(w))
print()

#C = B[:] #Initialize the target array. #CAUTION: With this instruction, every modification on C will be applied on B
C = np.zeros((2,2), dtype=int)# Instead we prefer to initialize an empty array same size than B
print('C=',C)
C[ListOfCoordinates[0]] = 1 # = C[(0,0)] Voir la liste ListOfCoordinates
C[ListOfCoordinates[1]] = 1 # = C[(1,0)] Voir la liste ListOfCoordinates

print('C=',C)
print('B=',B) 



[[1 2 4]
 [5 3 7]
 [8 3 6]]
[1 2 3 4 5 6 7 8]

B= [[3 7]
 [3 6]]

List= (array([0, 1]), array([0, 0]))
<class 'tuple'>

List= (array([], dtype=int64),)
<class 'tuple'>

ListOfCoordinates= [(0, 0), (1, 0)]
<class 'list'>

########################### FOR INFORMATION ###########################
ListArray= [[0 0]
 [1 0]]
<class 'numpy.ndarray'>

ListArray_row0= [0 0]
<class 'numpy.ndarray'>
ListArray_row0[0]= 0
<class 'numpy.int64'>

x= [3 6]
<class 'numpy.ndarray'>

y= 6
<class 'numpy.int64'>

z= [[3 6]
 [3 6]]
<class 'numpy.ndarray'>

#####################################################################

w= 6
<class 'numpy.int64'>

C= [[0 0]
 [0 0]]
C= [[1 0]
 [1 0]]
B= [[3 7]
 [3 6]]


/home/zebulon/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:28: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


In [2]:
print('unique_id_list_B=',np.unique(B))
print(type(np.unique(B)))

unique_id_list_B= [3 6 7]
<class 'numpy.ndarray'>


In [3]:
#### METHOD-1 ####

#RAPPEL A =[[1 2 4],[5 3 7],[8 3 6]]
#RAPPEL B =[[3 7],[3 6]]

#CAUTION: AVOID TO USE LOOPS AS MUCH AS POSSIBLE. Using loops you don't take advantage of the power of numpy! 
#Numpy computations are not optimized for loop operations!!


D = np.zeros((2,2), dtype=int)
B_unique_ID = np.unique(B)
for i in range(len(B_unique_ID)):
    List_i = np.where(B == B_unique_ID[i+1])
    ListOfCoordinates_i = list(zip(List_i[0], List_i[1]))
    #CAUTION (line below): 
        #If I have range(x) k will take values 0, 1, x-1 by default 
        #In this example first list generated ListOfCoordinates_i (i=0) has length 2 
        #--> range(len(ListOfCoordinates_i)- 1) = 1 --> k will only take value 0 and never move on!! 
        #--> DON'T put "-1"
    for k in range(len(ListOfCoordinates_i)): 
        #import pdb; pdb.set_trace() #Possibility to run debugger
        D[ListOfCoordinates_i[k]] = i + 1
print('New B=',D)
    



IndexError: index 3 is out of bounds for axis 0 with size 3

In [6]:
#### METHOD-2 ####

#Using as much as possible the array properties

E = np.zeros((2,2), dtype=int)
B_unique_ID = np.unique(B) #RAPPEL: Array [3 6 7]
Ngrains = len(np.unique(B)) #Length = 3
for p in range (Ngrains):
    Compare_Matrix = np.full((2,2),B_unique_ID[p]) #np.full creates a (2,2) matrix with constant value
    E = E + np.where(B == Compare_Matrix,p+1,0) # "==" compares element by element each matrix (True or False)
print(E)

[[1 3]
 [1 2]]


In [ ]:
import numpy as np
np.where([[True, False], [True, True]],[[1, 2], [3, 4]],[[9, 8], [7, 6]])

In [ ]:
np.full((2,2),10)

In [ ]:
print(Ngrains)