exercice to learn crystallography

In [53]:
from pymicro.crystal.lattice import Lattice, HklPlane
import numpy as np

In [54]:
# create a BCC lattice
a = 0.3306  # nm
al = Lattice.body_centered_cubic(a)
print(al._lengths)

[0.3306 0.3306 0.3306]


In [55]:
# create a (011) plane
p = HklPlane(0, 1, 1, al)

In [56]:
lambda_kev = 30
theta = p.bragg_angle(lambda_kev, verbose=True)


Bragg angle for 011 at 30.0 keV is 5.1 deg



In [57]:
p.bragg_angle?

In [58]:
phi1, Phi, phi2 = [103.517, 42.911, 266.452]

In [59]:
from pymicro.crystal.microstructure import Orientation
o = Orientation.from_euler([phi1, Phi, phi2])
print(o.orientation_matrix())

[[ 0.72522445  0.11069087 -0.67955649]
 [-0.18921622  0.98103102 -0.04213492]
 [ 0.66200205  0.15914039  0.7324122 ]]


In [60]:
o.dct_omega_angles(p, lambda_kev, verbose=True)


Bragg angle for 011 at 30.0 keV is 5.1 deg

A=1.430, B=-3.449, C=-0.378, Delta=55.2
the two omega values in degrees fulfilling the Bragg condition are (196.7, 28.3)


(196.7093136157989, 28.334546898386765)

In [61]:
p2 = p.friedel_pair()
o.dct_omega_angles(p2, lambda_kev, verbose=True)


Bragg angle for 0-1-1 at 30.0 keV is 5.1 deg

A=-1.430, B=3.449, C=-0.378, Delta=55.2
the two omega values in degrees fulfilling the Bragg condition are (16.7, 208.3)


(16.709313615798862, 208.33454689838678)

In [66]:
o_r = Orientation.Euler2Rodrigues([phi1, Phi, phi2])
print(o_r)

[-0.05853293  0.39013905  0.08721607]
