exercice to learn crystallography

In [19]:
import numpy as np

In [20]:
#MATERIAL PARAMETERS
#Lattice parameter
a = 0.3306  # in nm

#Miller indices
h = 0
k = 1
l = 1

#Considered grain Euler angles in radians
phi1 = np.radians(103.517)
PHI = np.radians(42.911)
phi2 = np.radians(266.452)

In [21]:
#Experimental parameters
Lambda_kev = 30 #in keV
Lambda_nm = 1.24/Lambda_kev #(1keV <=> 1.24nm) in nm 
print(Lambda_nm)

0.04133333333333333


In [22]:
#Interreticular distance 
dhkl = a/np.sqrt(np.square(h)+np.square(k)+np.square(l)) #in nm
print(dhkl)

0.2337695018602726


In [23]:
#Expected theta obtainable with pymicro or manually
theta = np.degrees(np.arcsin(Lambda_nm/(2*dhkl))) # in degrees
print(theta)

5.071921926301915


In [24]:
#Coefficients for matrix g
c1 = np.cos(phi1)
c2 = np.cos(phi2)
s1 = np.sin(phi1)
s2 = np.sin(phi2)
c = np.cos(PHI)
s = np.sin(PHI)


In [25]:
g = np.array([[c1*c2-s1*s2*c , s1*c2+c1*s2*c , s2*s],[-c1*s2-s1*c2*c , -s1*s2+c1*c2*c , c2*s],[s1*s , -c1*s , c]])
print (g)

[[ 0.72522445  0.11069087 -0.67955649]
 [-0.18921622  0.98103102 -0.04213492]
 [ 0.66200205  0.15914039  0.7324122 ]]


In [26]:
#Coefficients of Bragg diffraction condition.
#CAUTION: In the presentation slides there is a coefficient difference: all coefficients must be divided/
#by lattice parameter "a" to return the same result that in Pymicro :)
#However it does not change anything for the end result because it leads to the same equation to solve


#Also in Pymicro "C" is defined with np.rad(theta) which assumes that theta is in radians. But theta is in degrees/
#Why does it lead to the same result with this in mind?

A = (h*(c1*c2 - s1*s2*c) + k*(-c1*s2 - s1*c2*c) + l*(s1*s))/a
B = (-h*(s1*c2 - c1*s2*c) - k*(-s1*s2 + c1*c2*c) - l*(-c1*s))/a
C = -(2*np.sin(np.radians(theta))**2)/Lambda_nm

print(A)
print(B)
print(C)

1.4300841637935757
-3.448794343258281
-0.37817666876859707


In [27]:
B = (-h*(s1*c2 - c1*s2*c) - k*(-s1*s2 + c1*s2*c) - l*(-c1*s))/a
Bpymicro_code = -h / a * g[1, 0] - k / a * g[1, 1] - l / a * g[1, 2]
Bpymicro_out = -3.449

print(B)
print(Bpymicro_code)
print(Bpymicro_out)

-3.933571710347143
-2.8399761194329725
-3.449


In [28]:
#A and C match exactly with Pymicro values now
#PROBLEM: B does not match exactly: As per Pymicro it is expected to return -3.449!!!!

In [29]:
#Second order equation coefficients after variable change
coeffs = np.array([A+C , -2*B , C-A])


In [30]:
#Solve second order equation
t_array = np.roots(coeffs) 
print (t_array) 

[-7.70212009  0.22318923]


In [31]:
#Obtained angles w1 and w2 are angles of the sample fir a given grain.
#CAUTION: In general those angles are not 180° from each other.
#It is only true is a very specific grains orientations 
#(make a drawing for instance of a grain in topotomographic configuration)
#It must not be confused with the Friedel pairs angles. A grain will always diffract for 2 180° angles for a given plane if we follow one grain 
w1 = 2*np.degrees(np.arctan(t_array[0]))
w2 = 2*np.degrees(np.arctan(t_array[1]))
print(w1%360,w2)

194.795160817413 25.16319042360299


In [32]:
#Brute force method to solve equation with pymicro approach

Delta = (2*B)**2 - 4*(A+C)*(C-A)
print(Delta)

69.50043809270242


In [35]:
a=1/2*(phi1-phi2)
b=1/2*(phi1+phi2)

In [36]:
RRodrigues = np.array([np.tan((PHI/2)*(np.cos(a)/np.cos(b))) , np.tan((PHI/2)*(np.sin(a)/np.cos(b)))  , np.tan(b)])
print (RRodrigues)

[-0.05582894  0.38985503  0.08721607]


In [38]:
RRodriguesFranck = np.array([(1/np.linalg.norm(RRodrigues))*RRodrigues,2*np.arctan(np.linalg.norm(RRodrigues))])
print (RRodriguesFranck)

[array([-0.13840495,  0.96648565,  0.21621648]) 0.7668229506405789]
